#!groovy
//
// Job: iOS-MeetingSDK-Flutter
//
// Build the Flutter iOS IPA
//
// PREREQS:
//   - JAVA_HOME: C:\Program Files (x86)\Java\jre1.8.0_311
//   - git clone https://github.com/flutter/flutter.git -b stable (C:\Users\Administrator\src)
//     - add flutter\bin to PATH
//     - (one time) flutter doctor --android-licenses
//

@Library('shared-libs') _

pipeline {
    agent {
        label 'pomaci.iocom.com'
    }

    // triggers {
    //     // poll every minute
    //     pollSCM '* * * * *'
    // }

    environment {
        BUILD_YEAR = sh(returnStdout: true, script: "date +%y").trim()

        BUILD_MONTH = VersionNumber([
            versionNumberString: '${BUILD_MONTH,X}',
            worstResultForIncrement: 'SUCCESS'
        ])

        BUILD_DAY = VersionNumber([
            versionNumberString: '${BUILD_DAY,X}',
            worstResultForIncrement: 'SUCCESS'
        ])

        BUILDS_TODAY = VersionNumber([
            versionNumberString: '${BUILDS_TODAY}',
            worstResultForIncrement: 'SUCCESS'
        ])

        BUILD_VERSION = "${BUILD_YEAR}.${BUILD_MONTH}.${BUILD_DAY}.${BUILDS_TODAY}"
    }

    options {
        // timestamps in logs
        timestamps()
        
        // log rotation
        buildDiscarder(logRotator(numToKeepStr: '10'))
        
        // build timeout
        timeout(time: 30, unit: 'MINUTES')

        disableConcurrentBuilds()

        // colorize log output when a step is formatted
        ansiColor('xterm')

        // skip the default "Declarative: Checkout SCM" step
        skipDefaultCheckout()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout (
                    changelog: true,
                    poll: true,
                    scm: [
                        $class: 'GitSCM',
                        branches: [[name: '*/master']],
                        extensions: [
                            [
                                $class: 'CloneOption',
                                timeout: 20
                            ],
                            [
                                $class: 'CheckoutOption',
                                timeout: 20
                            ],
                            [
                                $class: 'CleanBeforeCheckout'
                            ]//,
                            // [
                            //     // pollSCM paths - add to the Jenkins UI configuration in
                            //     //   "Polling ignores commits in certain paths" - "Included Regions"
                            //     $class: 'PathRestriction',
                            //     includedRegions: """
                            //         android/.*\n
                            //         example/android/.*
                            //     """
                            // ]
                        ],
                        userRemoteConfigs: [[
                            credentialsId: 'jenkins-github',
                            url: 'git@github.com:visionable-public/FlutterMeetingSDK.git'
                        ]]
                    ]
                )
            }
        }

        stage('Init') {
            steps {
                script {
                    currentBuild.displayName = "${BUILD_VERSION}"

                    logInfo()
                }
            }
        }

        stage('Build') {
            steps {
                bat """
                    cd ${WORKSPACE}\\example

                    :: flutter doctor 2&> dev/null?

                    flutter build ipa --export-options-plist=path/to/ExportOptions.plist
                """
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts (
                    artifacts: """
                        example\\build\\app\\outputs\\flutter-ipa\\app-release.ipa
                    """,
                    onlyIfSuccessful: true,
                    defaultExcludes: true,
                    caseSensitive: true,
                    followSymlinks: true
                )
            }
        }
    }

    post {
        always {
            script {
                setEmailVars()
                sendEmail()
            }
        }
    }
}